# Generated by Django 6.0.2 on 2026-02-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
